### ISSUE TITLE
change name `mapping` to `model` or `cube`

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#111]
Probably `model` : I believe it is much closer to what we now have than `mapping`.

Raised in https://github.com/openspending/fiscal-data-package/issues/93#issue-120033382

Also https://github.com/dataprotocols/dataprotocols/issues/238

**Comment by pudo** [comment]
+1

**Comment by danfowler** [comment]
I'm generally in favor of this as "mapping" is probably insufficient for describing what is happening in the `mapping` object.  Beyond mapping physical ("source") columns to logical columns, the object describes how they relate to each other ("measures" v.s. "dimensions").  The fact that this object also gives fiscal types to dimensions makes me prefer the more generic `model` over `cube`.

**Comment by rgrp** [comment]
AGREED. Rename `mapping` to `model`.
