### ISSUE TITLE
Clarification on "precise code" terminology in parent examples

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#112]
http://fiscal.dataprotocols.org/spec/#classifications

The two descriptions and examples below are the way that `parent` is presented in the spec. On reading, I simply have no idea how to implement code around this, and my main point of confusion is "this will be the precise code" for the `code` attribute on both examples. I have no idea what "precise code" means in a general sense, nor, how it relates to a hierarchy.

Can we have some real world examples of how this would look on data?

> It is common for classifications to be hierarchical and have different levels. If this is present in your data and you wish to record it in the mapping, we recommend adopting the following structure using the keyword parent. In a hierarchical data structure, the parent keyword is used within an attribute to reference another attribute that serves as the first attribute’s parent. Here is an example of its use:

> "your-classification": {
>   "attributes": {
>     "code": {
>       // this will be the precise code
>       "source": "..."
>     },
>     "level1": {
>       "source": "..."
>     },
>     "level2": "{
>       "source": "...",
>       "parent": "level1"
>     }
>   }
> }

> If you have multiple attributes that exist at the same level of a hierarchy (e.g. an identifier for the level and its title), only use the “parent” key among the attributes that serve as the identifier for the level.

> "your-classification": {
>   "attributes": {
>     "code": {
>       // this will be the precise code
>       "source": "..."
>     },
>     "level1_id": {
>       "source": "..."
>     },
>     "level1_title": {
>       "source": "..."
>     },
>     "level2_id": "{
>       "source": "...",
>       "parent": "level1_id"
>     },
>     "level2_title": "{
>       "source": "..."
>     }
>   }
> }

**Comment by pwalsh** [comment]
@akariv how do you read this? How does it play out in the implementation you are working on for the API?

**Comment by akariv** [comment]
@pwalsh it is a little cryptic to me as well, and I can only guess the original intent.
I guess an example would be a data model in which transactions are from a specific spendings account (which might look like '02.04.26.73') you would call that id the 'precise code', and have attributes for the code '02' and it label, '04' and its label etc.
As for current implementation - on the server side the parent attribute is not used atm. However, I guess that on the client side it would come in very useful when presenting the user groups of options for filtering the dataset.

**Comment by pwalsh** [comment]
@akariv yes, I'm trying to implement it in the js lib for vis right now, exactly :).

If it is like you say, it is awfully ties to a particular use case of how `cofog` codes are represented. Further, it is not a "precise code", as, if anything, such a code would represent the lowest level in the hierarchy, and not something "outside" of the hierarchy, as the examples suggest. But, let's see what the original intentions were.

**Comment by rgrp** [comment]
AGREED. Will clarify in spec.
