### ISSUE TITLE
Names should be unique across measures and dimensions

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#113]
It would make things easier for code working with FDP if names of measures and dimensions were required to be unique across both measures and dimensions.

**Comment by rgrp** [comment]
Why? Could you explain a bit more as I am not clear why this would help code or the model? Only relation would be with the "fact" dimension which is now deprecated ;-0

**Comment by pwalsh** [comment]
In creating a new table to represent the logical model, each measure and dimension could be represented column. If measures and dimensions can have name clashes, then code for generating such a table has to handle that.

**Comment by danfowler** [comment]
+0

**Comment by rgrp** [comment]
@pwalsh i'm not sure i understand. Measures go direct onto fact table - not a separate table. The other dimensions either get their own table or you might inline (in some cases) onto fact probably doing `{dimension_table}_{attribute_name}`. Either way I don't get the clash.

**Comment by pwalsh** [comment]
A fact table would have a column that references a dimension table (a pointer to the dimension like a foreign key, or possibly inlined for single attribute dimensions). A reasonable name for such a column would be the name of the dimension. Therefore, if measures and dimensions have the same name (or can have...), code needs to handle such cases where names clash.

**Comment by rgrp** [comment]
@pwalsh ahh - yes i see though normally you might call the column after the pk column in the dimension table. Hmmm. Likely this will be 0.4 item not 0.3.

**Comment by akariv** [comment]
+1 to that (although might be tricky to automatically validate)

**Comment by pwalsh** [comment]
Moving to https://github.com/frictionlessdata/datapackage-fiscal/issues/3
