### ISSUE TITLE
constant -> default_value

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#115]
Currently in [the specification](http://fiscal.dataprotocols.org/spec/#dimensions), we can map an attribute in the logical model to a source column in the physical model (the CSV file).  Alternatively, we can provide a `constant` value that applies to all rows (e.g. a single year for datasets that implicitly span that year, see: https://github.com/openspending/fiscal-data-package/issues/59).  Looking through the old OpenSpending documentation, I see there was already some support for similar functionality with `default_value`:

https://github.com/openspending/openspending/blob/eb4989ce5c1870e5239aa44bd4da5f61627137f3/doc/model/design.rst

> column is used to define the source column where data for this attribute can be found when the dataset is loaded form a CSV file. If such a column cannot be found (or when it is empty), the system can fall back to a default_value, which will be used instead to fill up missing values. The default_value will not be used, however, if data is present but invalid (e.g. numeric columns with textual values, invalid dates). Such errors will never be loaded and yield an error. The same is true of attributes with empty values for which no default_value has been set (such as time in the example above).

Given that we already expressed the need for such a key in https://github.com/openspending/fiscal-data-package/issues/59, perhaps we can better align with previous work on the OpenSpending model by renaming `constant` to `default_value` and adopting its more flexible sematics.

**Comment by pwalsh** [comment]
@danfowler for me, the feature request that became `constant` rises from a different use case, and has a different meaning to `default_value`.

As you note above, `default_value` "fills in" missing values from the source data. However, `constant` is an *alternative*, static value which does not exist in source data. `constant` has no logic that says "take data from the field, and when the field is empty, take the default value". Rather says "there is no field but this is the static value".

I'd be wary of expanding the meaning of `constant` to cover the meaning implied by `default_value`.

**Comment by rgrp** [comment]
I'd +1 @pwalsh here and also wield "Occam's razor": where is the use case for the expanded functionality? If there is none, yet, let us leave this out.

**Comment by danfowler** [comment]
OK, closing.
