### ISSUE TITLE
Add CONTRIBUTING.md outlining expectations for contributors

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#117]
See: https://github.com/openspending/fiscal-data-package/issues/45

**Comment by danfowler** [comment]
@rgrp semi-related to this issue: I'm removing "next up" and "next version" labels in favor of heavier usage of Milestones

**Comment by rgrp** [comment]
I suggest this is v0.4 once we ship v0.3 in next few days.
