### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Vanuan** [openspending/fiscal-data-package#119]
Could you please add translation project to Transifex?

**Comment by danfowler** [comment]
Hi @Vanuan, thanks for the suggestion!  I see Open Knowledge is already using [the service](https://www.transifex.com/okfn/opendatahandbook/) to good effect.   This will be a very important to do, I think, once we've reached the next big milestone.

**Comment by cecilaki** [comment]
The old OpenSpending was on Transifex actually / [here](https://www.transifex.com/okfn/openspending/)

**Comment by danfowler** [comment]
@Vanuan can you tell me a bit more how you would use the translated spec?

**Comment by Vanuan** [comment]
Here, in Ukraine, there's a new law that requires to publish budget/spending data. But there are many formats, columns, categories, etc.
So I'd like to propose this as a format to use in Ukraine for publishing.

**Comment by akariv** [comment]
@danfowler Was anything done with regards to this request?

**Comment by rgrp** [comment]
@akariv remember i was handling this spec. Answer was that I do not think anything was done.

@Vanuan we would be up for getting a translation. Are you interested in doing it still?

**Comment by Vanuan** [comment]
Actually, there's already a draft translation on Google Docs: https://docs.google.com/document/d/1yjLJVbLW0Bj9amuuMlOKsUt97Dk41eTNUBsApZGwyJw/edit?usp=sharing

**Comment by pwalsh** [comment]
Hi @Vanuan 

Are you still interested in this? The spec text will change soon, so we can't use the existing translation, but if you would like to follow https://github.com/frictionlessdata/datapackage-fiscal/issues/4 we can sync up on this in the coming months.
