### ISSUE TITLE
Remove 'ocdid' as recommended attribute for location dimension

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#125]
> We RECOMMEND using a `location` dimension though attributes may also be applied directly onto another object (e.g. an entity). Here are attributes that `MAY` be applied either directly to an item or to an entity or other object associated to an item.

> * `code`: The internal or local geographicCode id based for the geographical region
* `title`: Name or title of the geographical region targeted by the budget item
* `codeList`: the geo codelist from which the geocode is drawn
* `ocdid`: The [Open Civic Data Division Identifier](http://docs.opencivicdata.org/en/latest/proposals/0002.html), if it exists, for the geographical region

@rgrp I understand it's only meant as a recommendation, but why is `ocdid` a special case?  Why not treat it as another example of a potential codeList: 

* `code`: The internal or local geographicCode id based for the geographical region
* `title`: Name or title of the geographical region targeted by the budget item
* `codeList`: the geo codelist from which the geocode is drawn **(e.g. "ocdid")**

**Comment by rgrp** [comment]
@danfowler agreed - i only had this as i had migrated from the original stuff Tryggvi had. I do not think we need to special case.
