### ISSUE TITLE
Change suggested "id" attributes to "code" attributes throughout spec

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#126]
We use both throughout and it is confusing.  

> - code: The internal code identifier for the economic classification.
> - title: Human-readable name of the economic classification of the budget item (i.e. the type of expenditure, e.g. purchases of goods, personnel expenses, etc.), drawn from the publisher’s chart of accounts.

and...

> - title: The title or name of the government entity legally responsible for spending the budgeted amount.
> - id: The internal code for the administrative entity.

It would also be helpful to harmonize the description of e.g. `title` elements ("human-readble name of...").

**Comment by timgdavies** [comment]
There is a difference between an ```id``` and a ```code``` so I'm not sure you should always use one or the other - but you should aim for consistency in usage.

E.g. A code is usually a shorthand for a label or classification; and identifier is usually attached to an entity, rather than labels/classifications of that entity.

**Comment by danfowler** [comment]
Thanks @timgdavies that was very helpful!  

I also wanted to be more careful about using `id` as an identifier for an actual thing in the world and `id` as relevant to the technical implementation (see: https://github.com/openspending/fiscal-data-package/issues/100#issuecomment-163350938)

What do you think @rgrp ?

**Comment by akariv** [comment]
bump.

**Comment by pwalsh** [comment]
Moving to https://github.com/frictionlessdata/datapackage-fiscal/issues/3
