### ISSUE TITLE
Can one column be mapped to more than one dimension?

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#128]
Part of the motivation behind the Fiscal Data Package specification is to require as little modification to the source data as possible.  It accomplishes this through the `mapping` object which allows columns in the "physical" model (source CSV) to be mapped to various attributes of dimensions in the "logical" model.  In the [BOOST Moldova dataset](https://github.com/openspending/fiscal-data-package-demos/tree/master/boost-moldova), we have data like this:

| year | admin1 | admin2 | amount |
|---|---|---|---|
| 2014 | Local | District Council Floresti | 1000 | 

In this case, `admin1` and `admin2` naturally map as attributes of an `administrative` dimension.  However, `admin2` also provides information that could naturally map to an attribute in the `location` dimension for e.g. geographic visualization.  Should we allow one column to be mapped to more than one dimension?

**Comment by pwalsh** [comment]
Yes.

**Comment by rgrp** [comment]
Yes.

**Comment by rgrp** [comment]
WONTFIX.

Is any action needed here on the spec? My answer would be no action is needed. Yes, you can do multiple mapping but probably quite rare. We could provide an example if this comes up a lot.
