### ISSUE TITLE
Removing Transaction Identifier

### ISSUE THREAD

**Issue by rgrp** [openspending/fiscal-data-package#131]
Spec (v0.3.0-alpha7) currently states:

> 
>The following attributes SHOULD be included wherever possible:
>
> * `id`: A globally unique identifier for the budget item. This `id` attribute will usually be located on the default `fact` dimension.

We propose removing this.

We would like there to be a unique identifier on budgets like this. However, so far, we have yet to see a budget or other fiscal dataset with this in. As such we propose removing this from the spec for the time being and only re-add when we are clear on need and form.

**Comment by timgdavies** [comment]
I would oppose removing this. 

I understand that source data does not often have such identifiers available in published datasets - but IDs dramatically improve the usability of data - and we should be strongly recommending that they are created and provided.

This is one of those cases where a standard has a political role in encouraging better data management practices inside government - and in pushing for improvements in data to meet user needs.

We have had similar experiences in Open Contracting, where identifiers often get seen as a challenge to start with and get a push-back, but as people see a standard asking for them, they quickly identify approaches to provide them.

**Comment by rgrp** [comment]
@timgdavies to be clear: I think this should and will be in the spec, probably reintroduced in v0.4 or v0.5. However, at present we do not have a single source dataset where this is present. So we are removing now and reintroducing once we are clear the best form and the best way to require this.

It also takes us back to the quality levels question - #95 and #124. Should we strictly require identifiers or make them a "level 2" requirement?
