### ISSUE TITLE
Which field in location dimension should be used for lookup?

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#135]
In [BOOST Moldova](https://github.com/openspending/fiscal-data-package-demos/blob/master/boost-moldova/datapackage.json), I have added a `location` dimension with one attribute.  In a case where I have more than one attribute, which attribute should be used for lookup on a `codeList`?

**Comment by pwalsh** [comment]
Close in favor of #140 ?

**Comment by danfowler** [comment]
True. Closing in favor of #140
