### ISSUE TITLE
validation error at Step 3 on OS packager

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/fiscal-data-package#136]
Hi to all. I have a question regarding an error on OS packager. As soon as I try to provide metadata on the dataset I am getting a "validation error." Is it that I'm not mapping the data correctly (only assigning amount and date)? I tried uploading this link: https://raw.githubusercontent.com/openspending/fiscal-data-package-demos/master/boost-moldova/data/boost-moldova-2014.csv. I would appreciate some guidance!
Please see a screenshot:
![validation error on os packager](https://cloud.githubusercontent.com/assets/17012538/12885663/69a8d114-ce70-11e5-8ec1-805302f63660.JPG)

**Comment by akariv** [comment]
This is an issue with Cosmopolitan changing its API.

**Comment by pwalsh** [comment]
Moved to https://github.com/openspending/openspending/issues/850
