### ISSUE TITLE
Support non-monetary measures as well

### ISSUE THREAD

**Issue by akariv** [openspending/fiscal-data-package#138]
Currently currency is a required property for a measure.

However, I've seen budget data which also defines non-monetary resource allocation, for example maximum allowed personnel (in FTE), contractor allowance (measured in man-months) or the more generic "amount" which is context dependent and could refer to student hours or vehicle numbers.

**Comment by pwalsh** [comment]
We made a decision a while back that measure == monetary amount. I agree that the examples you gave are useful and are related to "budgeting" in the broadest sense of the word, but they are not *fiscal* measures so I'd be -1 on moving beyond monetary measures for FDP.

**Comment by danfowler** [comment]
For reference: here's the decision: https://github.com/openspending/fiscal-data-package/issues/69

I agree with keeping strictly monetary measures.

**Comment by akariv** [comment]
Yes, but this is not the same case as in #69.

Here we have a measure which is monetary equivalent, can be aggregated and seems to be quite common, as we can see in the excellent "Budgeting and Budgetary Institutions" (published by the World Bank):

https://books.google.co.il/books?id=XCWCd2JcMJcC&lpg=PA302&ots=jGF0Vzzu_i&pg=PA301#v=onepage&q&f=false

Two side notes on this:
- Even for the case described in #69, I would argue we should allow such measures. Aggregation !== sum - it can also be average, min, max and other functions. So even if summing the absorption rates makes little sense, finding the maximum absorption rate is actually quite a reasonable query.
- We probably shouldn't limit ourselves in such ways in this early stage - we're not talking about a drastic change to the spec, but simply adding more units for describing numeric values...

@rgrp

**Comment by akariv** [comment]
I'd like to revisit this.

My suggestion is that each measure can either have a `currency` attribute or a `units` attribute. The units attribute can take one of a predefined list of values (to be defined, e.g. 'personnel' etc.). 
The emphasis here is that this new attribute is not intended to be used with general numeric columns, but only with "things" that can be aggregated / allocated / spent etc.

**Comment by jindrichmynarz** [comment]
In <http://openbudgets.eu> we initially thought that we'd need to support non-monetary measures as well, but working with datasets and discussing the topic with domain experts indicates so far that non-monetary measures are converted to monetary amounts in the published fiscal datasets; e.g., FTEs are converted to the amount of money needed to fund them.

**Comment by pwalsh** [comment]
Moving to https://github.com/frictionlessdata/datapackage-fiscal/issues/2
