### ISSUE TITLE
Remove suggested location attributes from "entity" dimension

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#139]
Currently in the spec, there is guidance suggesting adding the following attributes to an `entity` dimension.

> - location: Reference to a location dimension listing geographical region where administrative entity is located.
> - locationCode: code for geographical region where administrative entity is located.

I think it might be a useful simplification to remove this from the spec for now. For one thing, there is no treatment in the spec for how referencing one dimension from another would work ("Reference to a location dimension"): is it just a key pointing to an existing dimension with `dimensionType`: `location`?  If so, why would a `locationCode` be necessary?

I suggest fully removing until we have a specification or use case for the feature.  What do you think @rgrp @pwalsh @akariv ?

**Comment by danfowler** [comment]
@rgrp Bump. I would like to remove.

**Comment by rgrp** [comment]
We discussed on call. As said there I'm -1 / -0 on this at the moment without a proper issue on location changes detailed what's the problem now and how these changes will improve. At the moment there seem to be a mix of motivations: simplication (but removing functionality), a sense that location stuff does not support use cases we need.

My suggestion is we create that issue summarizing any input from @pwalsh @akariv etc on what is needed.

**Comment by akariv** [comment]
We should remove this and handle the location needs here the same way as I suggested in #140.

**Comment by rgrp** [comment]
@akariv i'm not sure what you are suggesting. Are you suggesting closing this issue or "removing" location attributes from entity? If the latter I'm still -0 until I understand clearly what would replace it and/or why we should not have this in the spec.

**Comment by akariv** [comment]
I suggest we accept this issue as 
1. Current wording is really not clear (what does `Reference to a location dimension` even mean?). Removing ambiguous parts is a good change.
2. Location in this spec as a whole needs an overhaul, so I wouldn't tie this small improvement with that possibly large modification.
(Also: 2.5. I'm reluctant on using *attribute names* for semantics. I find it better to use properties in these attributes (as `labelFor`, `parent`) instead of using the attribute names.)

**Comment by rgrp** [comment]
WONTFIX / INVALID.

**Comment by rgrp** [comment]
Actually think i just mis-read @akariv are you saying we *should* remove this stuff from the spec?

**Comment by pwalsh** [comment]
Moving to https://github.com/frictionlessdata/datapackage-fiscal/issues/3
