### ISSUE TITLE
'Funds source' classification

### ISSUE THREAD

**Issue by jazzido** [openspending/fiscal-data-package#142]
Most Argentine budgets use a *Fuente de Financiamiento* classification, in addition to the usual administrative, economic and functional.

I'm wondering if it would make sense to include it in the spec, and how common is that in other budgets.

For an example, see: http://bahia.presupuestoabierto.org/dataset_ejecucion_gastos_bahia_user_bahia?chart=barchart&dimension=Fuente%20de%20Financiamiento&measures=Aprobado

**Comment by rgrp** [comment]
@jazzido good suggestion. Certainly something to cover in the primer if not as a core field in the spec.

**Comment by danfowler** [comment]
@rgrp +1 

I added a PR acknowledging the limitations of FDP modeling in the appendix.

**Comment by rgrp** [comment]
WONTFIX.

@jazzido this is a really useful point but I'm not sure at the moment what we can meaningfully add to this spec that will efficiently and effectively address. @danfowler made a go at this in #152 but ultimately we do not think this helped a lot.

Please keep the comments and suggestions coming :-)
