### ISSUE TITLE
Move countryCode from top-level metadata to an attribute of the location dimension

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#147]
`countryCode` naturally belongs as an attribute of a `location` dimension.  By specifying `countryCode` this way, we have more flexibility and accuracy in describing a budget dataset that targets multiple countries (for example, [this dataset](https://github.com/openspending/fiscal-data-package-demos/blob/master/eu-allocations-per-ms-2014-2020/datapackage.json#L7) describes allocations for several countries, but the link between the allocation and the country is lost when specified as a top-level array).  Used in combination with `constant`, the behavior of a top-level `countryCode` (i.e. in which all lines refer to the same country) can be retained.

**Comment by rgrp** [comment]
I am really not sure on this. I thought countryCode at top level is about describing the overall dataset (i.e. this dataset is about spending in the US). This change seems to be doing something different which is about how location dimensions work ...

**Comment by danfowler** [comment]
Without this change, we have two sources of location information for spending in a given FDP: within the location dimension and at the top-level.  This tries to simplify things a bit by only allowing location information through a location dimension.

And yes, it is the simplest start of describing how location dimensions could work.

**Comment by danfowler** [comment]
@rgrp bump. we already have `constant` to describe data in the overall dataset.

See: https://github.com/openspending/fiscal-data-package/issues/59

**Comment by rgrp** [comment]
@danfowler i explained this on the call. This was general metadata at top level. It was not intended to qualify location stuff. I do not understand use of `constant` here. I'm currently a clear -1 on this.

I think it is ok and valuable to have two distinct things: general statement that this is related to country X (top-level metadata) and adding standard location info in a column or elsewhere (not yet sure of this use case).

**Comment by akariv** [comment]
The way I see it, indeed all metadata properties can also be represented as `constant` dimensions.
However, from a practical point of view it makes more sense to keep them as properties as it keeps the packages more readable, more easily managed and it simplifies validation a great deal.

Also, why only location? We could argue that the same logic applies to the period meta attribute vs. date/time dimensions. That is, requiring the package to both define a date/time dimension as well as specify the `period` meta attribute is redundant, as the former implies the latter.

I would leave it to implementors to decide which meta-attributes should also be represented as `constant` attributes (if at all).

**Comment by rgrp** [comment]
WONTFIX. Agreed with @akariv on this: there is no reason to remove this as top-level descriptor metadata.
