### ISSUE TITLE
Remove references to adding location attributes to non-location dimensions

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#149]
In the current `location` dimension, [there is language](http://fiscal.dataprotocols.org/spec/#location) that suggests one can add location attributes to dimensions other than a `location` dimension.  

> Note when applying these as attributes directly on an object we suggest prefixing each value with `geo` so you would have `geoCode` rather than `code` etc.

This is [generally considered confusing](https://github.com/openspending/fiscal-data-package/pull/148/files#r55992479) and potentially not useful, so moving to remove.

**Comment by akariv** [comment]
@danfowler should we close this?

**Comment by rgrp** [comment]
WONTFIX / DUPLICATE of #139.
