### ISSUE TITLE
Links to ID schemas

### ISSUE THREAD

**Issue by nmashton** [openspending/fiscal-data-package#15]
Sarah Bird from Open Contracting observed that the BDP spec's numerical ID fields currently aren't really good for much: they're just strings, and without any further context, such strings can't be used for linking up datasets (etc.).

She walked me through the Open Contracting spec's approach to ID fields, which divides them up into four:
- freeform text
- freeform identifier
- link to schema
- URI

She suggested that we should take a similar approach with our spec, at least adding in some kind of link to the schema (which I suggested we could put in the metadata for the relevant field). This would facilitate joining up datasets by turning freeform IDs into meaningful identifiers.

Including a feature in the spec that allows budgets and contracts to be linked up would be a huge win for both specifications, so it's important that this feature be included in the next revision.

How exactly this should work on a technical level is still up for discussion (holding a conversation on the stairs outside a bar while jetlagged, which is how this idea was floated, is not really the best way to nail down technical details)—and clearly Sarah Bird should be invited to be the leading voice in this discussion.

Conceivably the "schema link" could point to some sort of vocabulary or codesheet, and the link URL could serve as a namespace prefix on the ID itself. (This would obviate any need for an additional URI field.)

**Comment by pwalsh** [comment]
Moving to https://github.com/frictionlessdata/datapackage-fiscal/issues/3 and https://github.com/frictionlessdata/datapackage-fiscal/issues/7
