### ISSUE TITLE
Supporting directions other than "expenditure" and "revenue"

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#155]
Specifically for "assets" and "liabilities": see previous discussion started by @stevage :

https://discuss.okfn.org/t/supporting-assets-and-liabilities-needed-for-openeconomy-org-au/452

Brought up also in the context of where in FDP `direction` should be specified: https://github.com/openspending/fiscal-data-package/issues/37

**Comment by akariv** [comment]
Any reason not to add this?
Also based on the US budget we probably need `authority` & `outlays` as well.
(https://github.com/WhiteHouse/budgetdata/blob/2016/USER_GUIDE.md)

**Comment by rgrp** [comment]
@akariv 

* what is an `authority`? I don't think it is a direction in the sense we have here.
* `outlay` for me is just a synonym for expenditure (and `receipts` which they use is a synonym for `revenue`)

Re assets and liabilities happy to add these though they are somewhat different from a direction in conception ...

**Comment by akariv** [comment]
That's a good question, and from my understanding these terms are not just synonyms but hold some extra semantics.

According to this source (https://sethssources.wordpress.com/2012/07/15/budget-authority-vs-outlays/):
> Outlays for fiscal 2013 reflect the actual amount of money the federal government will spend in 2013. The outlays figure for 2013 includes some unspent money that was authorized in previous budgets and excludes some spending approved in 2013 that will carry over into 2014 and beyond. Budget authority for 2013 excludes any funding authorized in previous years but includes money authorized in 2013 that will carry over into the future.
>  - Use outlays when you are referring to the overall size of the fiscal budget for a given year or when you want to show the deficit or surplus.
>  - Use budget authority when you want to show the effect that the administration’s policy decisions that year had on various agencies or functions of the federal government. Because it doesn’t count money approved in previous years, budget authority gives you a clearer picture of whether an administration is cutting or increasing funding for a department.

There are some insightful diagrams in there as well.

**Comment by stevage** [comment]
From that definition, "outlays" and "authorities" both sound like `phase`s, with direction `expenditure`. The semantics of those phases would capture the details about fiscal years, carryover funding etc. (Our current spec limits `phase` to one of four values, which match the UK budgetary process - seems a little bit odd, really.)

So what's our definition of "direction"? Something like: "Adding two amounts with the same direction yields another amount with the same direction. Adding two amounts with different directions yields nonsense." But that's self-referential...

In any case, adding `assets` and `liabilities` rounds out the number of directions to 4 pretty fundamental types on two axes: positive or negative, change or total.

**Comment by rgrp** [comment]
@akariv on that basis "budgeted" sounds more like the phases e.g. `planned` vs `actual`.

@stevage current `phase` choices were not modelled on UK afaik but on what we were told by the budget experts though we may have missed some and happy to add more (but that should be a separate issue i think!)

**Comment by rgrp** [comment]
@stevage are you happy to do a PR for adding assets and liabilities to options for direction with a short definition for each.

**Comment by stevage** [comment]
Yes, I started work on one. One thing I got a little stuck on was whether to:

a) Make the four directions "first class" and equally prominent throughout (ie, changing every reference to "expenditure or revenue" to "expenditure, revenue, assets or liabilities"); or 
b) Strongly prioritise expenditure and revenue, with a couple of notes in specific places that assets and liabilities are also supported.

I'd actually lean towards b, as I think this kind of data will be relatively uncommon, and it makes the doc a bit cumbersome otherwise.

**Comment by rgrp** [comment]
@stevage agree and definitely lean towards (b).

**Comment by jindrichmynarz** [comment]
In <http://openbudgets.eu> we don't label the distinction between expenditure and revenue as "direction", but instead as "operation character" (see [p. 33](http://openbudgets.eu/assets/deliverables/D1.4.pdf) and [here](https://github.com/openbudgets/data-model/blob/master/budget/budget-components.ttl#L87-L92)). The more generic label allows us to extend this dimension to other concepts if needed. For example, we discussed adding "financing" for transactions in assets and liabilities (as discussed above). So far, we haven't needed this concept, so we distinguish only expenditure and revenue.

**Comment by pwalsh** [comment]
Agree with jindrich that operation character is better/more generic for expansion beyond expenditure and revenue.

**Comment by pwalsh** [comment]
Moved to https://github.com/frictionlessdata/datapackage-fiscal/issues/2
