### ISSUE TITLE
Phase names for revenue data

### ISSUE THREAD

**Issue by joffemd** [openspending/fiscal-data-package#156]
The Phase options are currently as follows:  proposed, approved, adjusted, executed.

These fit budgets very well, but don't apply to Revenue data sets.  Is it possible to add the following options:  "Actual", "Estimated" and "Projected"?

**Comment by akariv** [comment]
We should definitely allow more options for this property.

Also @cecile and @victoriavlad, this relates to the comments we received about different phases in South American countries (as well as other phases we've seen in various datasets). Could we create a list of what we know to be missing so we can update the spec accordingly?

**Comment by rgrp** [comment]
@akariv @joffemd  👍 

@joffemd do you have any more before you actual, estimated and projected?

**Comment by joffemd** [comment]
Rufus:  Those are the only three I can think of.

**Comment by cecilaki** [comment]
Based on feedback received from the MoF of Mexico and regarding Expenditure phases, I would recommend updating the spec with the following phases: `Committed`, `Accrued`, `Paid` and `Arrears`, in addition with the existing `proposed`, `approved`, `adjusted` and `executed`.

**Comment by pwalsh** [comment]
TBH I do not think we can solve this by adding additional specific terms as phases. We likely need some type of "phase set" concept, with the ability to choose from different phase sets, which could become incredibly complicated.

**Comment by rgrp** [comment]
@cecilaki are those `phases` or indicators of something else e.g. `arrears` seems not to be a phase so much as a description of an amount. Also is `committed` not a synonym for `approved`. And `accrued` is usually something from a chart of accounts definition (accrued expenses etc).

**Comment by cecilaki** [comment]
@rgrp those are phases actually used to describe the existing execution of the federal budget and is feedback received based on actual data uploaded against the spec.

**Comment by pwalsh** [comment]
Moved to https://github.com/frictionlessdata/datapackage-fiscal/issues/1
