### ISSUE TITLE
Is the spec still alive?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [openspending/fiscal-data-package#158]
Nor http://specs.frictionlessdata.io/ (former dataprotocols.org), nor http://specs.okfnlabs.org/ (which is linked as "the new home for DataProtocols" mention Fiscal Data Package. 

Does it mean you're planning to end supporting it?

I wonder also: is it used anywhere in production?

I'm asking because we're thinking about recommending this spec around transparencee.org community, and implement it practically in budget portal we are developing in Georgia.

**Comment by danfowler** [comment]
Hello @KrzysztofMadejski this was an oversight.  The Fiscal Data Package is very much alive and will be linked to from http://specs.frictionlessdata.io/ 

It is currently being used in production on http://next.openspending.org/

**Comment by KrzysztofMadejski** [comment]
That's relieving! Thank you @danfowler.
