### ISSUE TITLE
Specification's license

### ISSUE THREAD

**Issue by KrzysztofMadejski** [openspending/fiscal-data-package#159]
Excuse me for being picky. :)

Readme of this repo mentions http://creativecommons.org/licenses/by-sa/4.0/ license, whereas http://fiscal.dataprotocols.org/spec/ in the footer mentions http://creativecommons.org/licenses/by/3.0/. Which one is the right one?

**Comment by danfowler** [comment]
Excellent catch.  Will fix.  Please do keep it coming!

**Comment by KrzysztofMadejski** [comment]
I'd vote for putting the license in LICENSE.md file so Github "understands it".

**Comment by pwalsh** [comment]
The spec has move to live with all other Frictionless Data specs here (and has a license): https://github.com/frictionlessdata/specs/tree/master/content/fiscal-data-package
