### ISSUE TITLE
Make repo submodule of https://github.com/frictionlessdata/specs

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#160]
- [x] Move current `index.md` to `README.md`
- [x] Move actual spec from `/spec/index.md` to root `/index.md`
- [x] Move some FDP-relevant bits from `/_includes/` to general **frictionlessdata/specs** site
- [x] Move FDP-relevant bits from /css/ to general **frictionlessdata/specs** site
- [x] Remove Jekyll/GitHub Pages files (_layouts, _includes, css, CNAME, _config.yml)
- [x] Remove Fiscal Data Package Google Analytics entry
- [ ] Remove gh-pages branch (obviates #162)

The end result should looks like the below.  Only the contents of the spec live here without any extra GitHub Pages machinery, but when we submodule, the spec is published at http://specs.frictionlessdata.io/fiscal-data-package/

    /
    index.md (contains actual specification, current content of /spec/index.md)
    README.md (introduces FDP + add appropriate external links, current content of /index.md)
    CONTRIBUTING.md (unchanged)
    LICENSE.md (unchanged)
    0.3/index.md
    0.2/index.md
    0.1/index.md
    examples/ (unchanged)
    tests/ (OPTIONAL ADDITION: tests contents of examples for conformance with spec)
    fiscal-data-package.json (OPTIONAL ADDITION: home for schema that validates the spec)

Then we add **openspending/fiscal-data-package** as submodule of **frictionlessdata/specs** so that "Fiscal Data Package" is listed as profile of Data Package along with Tabular Data Package.

**Comment by danfowler** [comment]
@pwalsh I'm looking at this as a general way to publish an promote "profiles" for Data Packages (at least the ones we control).

**Comment by pwalsh** [comment]
LGTM

**Comment by rgrp** [comment]
LGTM

**Comment by danfowler** [comment]
Great. https://github.com/frictionlessdata/specs/pull/299 was merged a bit prematurely, so now there's a broken link on the specs site, but this ready to go so I will finish this off today.

@akariv @VictoriaVlad @DianaMPG

**Comment by danfowler** [comment]
This was done: http://specs.frictionlessdata.io/fiscal-data-package/
