### ISSUE TITLE
fiscalYear isn't a date

### ISSUE THREAD

**Issue by pudo** [openspending/fiscal-data-package#19]
In it's simplest case, it's a date range (e.g. one year, two years starting in July, or seven years as in the case of the MFF). But a budget can also contain different data for different years, e.g. a budget for the next year and a financial framework for the one after that. Maybe to complex to model at the beginning, though.

**Comment by danfowler** [comment]
@rgrp This has been adopted.  Can this be closed?

**Comment by rgrp** [comment]
FIXED. (A while ago).
