### ISSUE TITLE
Add more guidance into datapackage section for versioning / maintaining historical data packages.

### ISSUE THREAD

**Issue by birdsarah** [openspending/fiscal-data-package#22]
In [open contracting](http://ocds.open-contracting.org/standard/) we want to be able to link to budget data packages and items in a budget data package to provide a link between the budget and the procurement against it.

The current way we're accomplishing this, although input is greatly received, is simply through specifying a URI to the budgetDataPackage and the id of the budget item. 

However, I can imagine a scenario where each year a publisher overwrites their annual budget data package.

Obviously we would want links to budget data packages to live on for historical referencing and so it would be great to see this documented in the specification as an area for compliance.

**Comment by danfowler** [comment]
Hi @birdsarah, I wonder if this isn't an [issue](https://github.com/dataprotocols/dataprotocols/issues) for the broader data package specification as I'm sure there are other types of data for which people may want persistence in their URIs for historical reference.  What do you think @rgrp?

**Comment by rgrp** [comment]
@birdsarah @danfowler my sense is this is probably a recommended "pattern" rather than a part of the spec. Really useful point and one we could definitely provide guidance on but a WONTFIX in terms of the spec itself (though we should add a note somewhere to add this to the guide - cf also point a) in #72)

**Comment by danfowler** [comment]
OK, I am closing this in favor of forthcoming work on guidance/documentation in #72.  Thanks very much for your input @birdsarah :).
