### ISSUE TITLE
Clarification of status field

### ISSUE THREAD

**Issue by jpmckinney** [openspending/fiscal-data-package#24]
Status can be "proposed", "approved", "adjusted", or "executed". Can a "typical" budget process be described so that these statuses are clear? Right now there's just:

>Data can come from any stage in the budget cycle (proposal, approval, adjustment, execution). This includes three different types of planned / projected budget items (proposal, approval, adjustment) and one representing actual completed transactions (execution).

Elsewhere in the spec I see `dataBudgeted`, `amountBudgeted`, `dateAdjusted`, `amountAdjusted` and `dateReported`. Is "budgeted" here what's been "approved", and is "reported" what's been "executed"? Should "Budgeted" be changed to "Approved" and "Reported" to "Executed" to better align with the status field?

Related: #7 recommends adding some descriptive text in cases where the budget package skips all earlier statuses and is simply executed.

**Comment by rgrp** [comment]
I think this is now duplicate / can be merged with #35  (also some concerns are now obsolete as we are less prescriptive on data content)
