### ISSUE TITLE
Explain differences between aggregated and transactional

### ISSUE THREAD

**Issue by jpmckinney** [openspending/fiscal-data-package#27]
I'm not sure why the following differences exist in expenditures:

* `cofog` is required in aggregated but not transactional
* `financialSource` and `type` exists in aggregated but not transactional

(I'd be happy to drop `financialSource` and `type` entirely)

**Comment by rgrp** [comment]
I think this is now FIXED / OBSOLETE with work in v0.3 and esp in #34.
