### ISSUE TITLE
Property name suggestions

### ISSUE THREAD

**Issue by jpmckinney** [openspending/fiscal-data-package#28]
* If `location` is restricted to country, then I would rename to `countryCode` (as in the Geonames ontology).
* `admin`: I find this a strange way to refer to a government entity. If we're referring to the administrator of an account, why not be expressive and name it `administrator`?
* `cofog`: To ensure people enter `01.1` instead of "Executive and legislative organs, financial and fiscal affairs, external affairs", rename it to `cofogCode`, which is how the UN refers to these.
* `economic`, `functional`: Whenever I read these, I think "economic what?" Why not expand to `economicClassification` and `functionalClassification`?
* `financialSource`: this field is defined to be a classification. "financial source" makes me think of specific sources like "IMF", not classes of sources like "aid". A clearer name is needed.
* `fund` (`fundID`): `account` is a more common accounting term.
* `geocode`: too easily confused with geocoding (finding lat/lngs). Why not the more expressive `geographicCode` (if it's meant to be a code)?
* `purchaserID` (`purchaserOrgID`): Not all expenditures are purchases. `procuringEntityID` (used by Open Contracting) would be more appropriate. Further, in Canada, the purchaser is literally Her Majesty the Queen in Right of Canada, but the organizations we care about are the procuring organization (usually Public Works and Government Services Canada) and the administering organization (whichever department).
* `type`: with valid values "personnel", "non-personnel recurrent", "capital", "other". Not sure what these values mean. Once clarified, I might suggest a better term than the generic `type`.

**Comment by rgrp** [comment]
Some of these have been implemented e.g. countryCode and some are now not relevant as we have removed item from spec. Keeping open as need to fully review and some items may be reintrodued.

**Comment by rgrp** [comment]
FIXED / INVALID. with the refactor in #34 and associated work in v0.3 most of these changes are done or no longer valid.
