### ISSUE TITLE
Multiple years/granularity/status on a single data package

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/fiscal-data-package#3]
**Disclaimer**: I'll point out a specific use case with which separating the budget by year/granularity/status makes it more difficult to produce the data. I'm not suggesting that it should be changed in the BDP, but just explaining my use case.

On http://cameroon.openspending.org and http://orcamento.inesc.org.br, we have a few visualizations using fiscal data. Everything on these sites is coming from OpenSpending: there's no other database. Taking the Cameroon site as an example, we have two main datasets: https://openspending.org/cm-budgets and https://openspending.org/cm-pib .

The `cm-budgets` contain the budget data for every councils in Cameroon, in every year, and granularity, and status. To sum it up, it contains everything related to council budgets. We've done this because when a new year or a new council is added, the site automatically uses the new data. There's no need to configure it to use a new dataset name, as it's all in a single place. So, the process for adding data is just to add stuff to that dataset. The website automatically uses whatever data is available.

If we followed the current BDP proposal, we would have a single dataset for each council, year, granularity, etc. There can't be a BDP for multiple years right now, as far as I can see. This would make it more difficult to update the site, because we would need to add in some configuration file the datasets available (e.g. cm-tignere-2009-expenses, cm-tignere-2009-revenue, cm-tignere-2010-expenses, ...).

**Comment by rgrp** [comment]
DUPLICATE now of multiple other issues on this e.g. #39
