### ISSUE TITLE
Switch to GFSM 2014 once published

### ISSUE THREAD

**Issue by jpmckinney** [openspending/fiscal-data-package#30]
It's currently a pre-publication draft. 

http://www.imf.org/external/np/sta/gfsm/

**Comment by tryggvib** [comment]
+1 on making the switch once published. Hopefully that happens before we release the second version of budget data package (no date set for now).

**Comment by rgrp** [comment]
This is now related /dependent on #34

**Comment by danfowler** [comment]
This is still technically in pre-publication draft, though the text is finalized.  Since the table references in the spec remain the same, and the actual classification code example remains the same, I will create a PR that updates the spec to refer to the newer version.
