### ISSUE TITLE
Coordination with related efforts - Open Contracting, DATA Act, etc

### ISSUE THREAD

**Issue by philipashlock** [openspending/fiscal-data-package#31]
I'm not intimately familiar with this effort or the technical details of [Open Contracting](http://standard.open-contracting.org/), but I've seen mention of Open Contracting in a few other issues and I wondered if there was an overview of how the efforts relate to one another and where there might be common elements. 

I also wanted to bring up a new related effort to create the data standard to be used for tracking spending within the US Federal Government (thru the [DATA Act](http://en.wikipedia.org/wiki/Digital_Accountability_and_Transparency_Act_of_2014)) which is also being managed on on github. See [fedspendingtransparency.github.io](http://fedspendingtransparency.github.io/) and their [issue tracker](https://github.com/fedspendingtransparency/fedspendingtransparency.github.io/issues)

**Comment by tryggvib** [comment]
Thanks. We've already been working a bit with and around the Open Contracting. 

The US federal spending effort seems very much aligned with our efforts, we should definitely try to coordinate with them somehow.

**Comment by rgrp** [comment]
FIXED. Closing as this is in progress.
