### ISSUE TITLE
Consider renaming status to "phase"

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#35]
Less ambiguous than status. Used in the current [RDF Budget Model for Open Budgets](https://github.com/openbudgets/data-model)

**Comment by rgrp** [comment]
Current options are:

* `moment`
* `phase`

We could / should double check with WB and IBP folks on this one.

My guess is we also prefix with e.g. `budget` so `budgetMoment` or `budgetPhase`

**Comment by danfowler** [comment]
@rgrp yeah, I can see what WB preference is on tonight's call

**Comment by danfowler** [comment]
@pwalsh @rgrp "budgetPhase"

**Comment by pwalsh** [comment]
if we are introducing a distinction like `budget*` then we might also want to consider other properties, and see if they are budget-specific (or aggregate-data specific?). This also suggests that we might want to be explicit about expected properties in relation to `granularity` (we expect X when granularity is "transactional", or property Y has no effect when granularity is "transactional"). Probably discussion for a different issue though.

**Comment by rgrp** [comment]
Do we go for `phase` or `budgetPhase` - i'm slightly inclining to the former for reasons that @pwalsh highlights. Not sure it matters a lot so happy to have a quick +1 / -1 etc on `phase` vs `budgetPhase`

**Comment by danfowler** [comment]
+1 on `phase`

**Comment by pwalsh** [comment]
+ 1 on `phase`

**Comment by rgrp** [comment]
Agreed to rename to phase. Will also move down to measure.

**Comment by rgrp** [comment]
In addition status will move out of descriptor metadata to avoid duplication as it is on measures.
