### ISSUE TITLE
On "status"

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#38]
`status` is currently declared at the package level.

* Should we consider it as a property of resources?
  * Should we allow both, where a declaration on a resource overrides that of the package?
* If there is no default, how should the data be understood in the absence of the `status` property?

Also, see #35

**Comment by danfowler** [comment]
@pwalsh @rgrp my current understanding suggests that the current sole purpose of having multiple resources in a fiscal data package is to allow a single dataset to be normalized across several tables. If that understanding is correct, I don't see how different resources could have different statuses.

Much of the BOOST data we have been working with has multiple statuses on each line: approved, adjusted, executed.  Given that top-level status is only a `MAY` property, my inclination for these examples is to just eliminate it from the datapackage.json, instead representing those statuses as different measures of a given spending line.  For these cases, could `status` also be a property of a given measure?

**Comment by pwalsh** [comment]
@danfowler essentially, status is a property of a measure. I have examples of data where each line has multiple measures, where each measure maps to a `budgetPhase`, or `status`. ([Example](https://docs.google.com/spreadsheets/d/1rcNq4hcutZNWTaKrpUQhtplGW1mMCiQDM_PFZ3KxX94/edit#gid=8): columns H and I). This is consistent with what you have in the BOOST data.

However, much data only has a single measure, and if the FDP is type `aggregate`, for example, we'd probably want to set the status on the package as the source file can't tell us (in this regard, it is exactly like `fiscalPeriod`).

**Comment by danfowler** [comment]
@pwalsh @rgrp so for the example of a dataset with multiple `status` per line, should an executive decision be made at the package level to represent the "main" `status` (e.g. `approved`) while still exposing all measures/statuses through the mapping?

**Comment by pwalsh** [comment]
@danfowler I don't see how that could make sense. How would one understand what the "main" measure would be?

**Comment by rgrp** [comment]
@danfowler my understanding was that the status (which is getting renamed) would be set to an array. My sense is that status is still useful even where on measures as summary metadata that is directly accessible without delving into the measures.

**Comment by danfowler** [comment]
The “status” concept as an array does I think solve this issue.

**Comment by rgrp** [comment]
DUPLICATE now of #35
