### ISSUE TITLE
Change field label "project" to "task" ?

### ISSUE THREAD

**Issue by pzwsk** [openspending/fiscal-data-package#4]
In the description it is written "Name of the project underwriting the budget item. A project is an indivisible activity with a dedicated budget and fixed schedule." However I've been found with real budget classification where project was not the most granular activity. I would therefore suggest to use a more neutral term such as "task to identify the most granular activity in the Budget Data Package an as such avoid confusion when the term project is used.

**Comment by rgrp** [comment]
With some of the project / program work reintroduced, albeit in simpler form, in #34 it would be worth looking at this again.

@pzwsk @jpmckinney do you have any thoughts on improvements to current recommendations in http://fiscal.dataprotocols.org/spec/#programs-and-projects?

**Comment by jpmckinney** [comment]
Won't it be confusing for a program to have a `dimensionType` of `project`?

**Comment by rgrp** [comment]
@jpmckinney we are not planning to distinguish project or program as dimension types since they are the same "type" of object. Do you have a suggestion on how to make this clearer?

**Comment by danfowler** [comment]
@rgrp is there a reason why programs (or sub-programs) and projects can't be defined simply as various levels of a `classification` dimension with a `classificationType` type of `program`?  Why treat programs/projects separately if they share qualities with other budget classifications?

<img width="787" alt="screen shot 2015-10-20 at 12 01 40" src="https://cloud.githubusercontent.com/assets/772616/10602684/6ddee03e-7722-11e5-988b-18730e9b38e2.png">

Also from: https://www.imf.org/external/pubs/ft/tnm/2009/tnm0906.pdf

**Comment by pzwsk** [comment]
I think @danfowler 's remark is worth considering.

**Comment by pzwsk** [comment]
Also, I am confused by this paragraph in the Appendix: "Categorizing and organizing the data is more about describing it from the bigger perspective than breaking it down into detailed components and the Fiscal Data Package specification tries to take that into account by including top level hierarchies and generalised classification systems but there is still a possibility to go into details by supplying a good description of every row in the budget data."

In my view, the ultimate objective of the Fiscal Data Package is to help build (investigate) the missing links beween transactional level data and aggregated levels budget data. For this reason, the possibility to represent the exact number of levels within a budget (i.e. to have N-levels of sub-hierarchy for a program) remains an important feature.

**Comment by rgrp** [comment]
@pzwsk ok let's distinguish two things:

- Having levels of programs / projects. I think we should support this and we eliminate any distinction between project and program (which currently have some rough correspondence to hierarchy). This would also simplify terminology.
- Where program / project is best considered as a type of classification. The only reason I've been cautious is seeing programs/projects as distinct object types (cf connection with e.g. IATI where programs are first class objects with a bunch of associated info e.g. start, end dates, owners etc).

What do people think? Also if we were to merge "program / project" which do we go for? The default would be to stick with `project` as that is the current label for `dimensionType` but in some ways i like `program` as project already has a lot of meaning for people.

**Comment by pwalsh** [comment]
About @danfowler's remark that classification could be used: not agreed on that. I understand the point because in form, they are almost the same, but I think they have distinct meaning (and structure as @rgrp points out), and we want to develop them distinctly going forward for comparative analysis, etc.:

About program/projects more generally: `program` works for me, as a container that holds all levels in that heirarchy.

**Comment by jpmckinney** [comment]
Some publishers will only be able to go so deep. For instance, based on Canada's present data, "project" would definitely be a bad way of describing their "program activities" (in their nomenclature), which are their lowest units of aggregation. If we want to merge "project" and "program" into one, I think it's obvious that we can't just pick one of the two terms ("apple" or "orange"); we need a more general term that includes both ("fruit").

Now, the concepts that includes both "project" and "program" are not as central to the English language as that of "fruit", so it's very likely we won't arrive at a beautiful, shining term that unites the two - but we'll at least avoid a situation in which we ask people to call apples "oranges". For now, the only term I can think of is "activity".

**Comment by rgrp** [comment]
@pzwsk any thoughts

@jpmckinney btw could you link us the Canadian dataset you are describing - we can then add it to https://github.com/os-data/registry and try using it.

**Comment by rgrp** [comment]
AGREED atm:

* Consolidate into one term (do not have **both** project and program) BUT not clear yet on what term!
* Introduce levels here like we have on classification
* Will **not** merge with classification

**Comment by jpmckinney** [comment]
I'll try to find the dataset again, but Canada's data catalog is marvelously difficult to search.

**Comment by danfowler** [comment]
Proposed: use `activity` as term.

**Comment by pwalsh** [comment]
+1 `activity`
