### ISSUE TITLE
"properties" or "fields" for dimension attributes?

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#40]
Both are used in the current examples

* `mapping.date.properties.year`
* `mapping.payee.fields.id`

**Comment by rgrp** [comment]
that is a bug. Do you have a preference. I was going for fields to avoid confusion with JSON term "properties"

**Comment by pwalsh** [comment]
I think fields is great, I just wasn't sure which we were aligning to.

**Comment by rgrp** [comment]
We want to change to `attributes` from `fields` to distinguish logical from physical model.
