### ISSUE TITLE
dimension and dimensionType

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#44]
The current spec for this is:

```
...
"mapping": {
  "ownDimensionName": {
    "dimensionType": "datetime|entity|classification|project|{null which means custom}"
  }
}
...
```

But why not:

```
...
"mapping": {
  "dimensions": { // see https://github.com/openspending/fiscal-data-package/issues/43
    "datetime|entity|classification|project|{null which means custom}": { # the identifier for the dimension is the type
      "name": "ownDimensionName" // required
    }
  }
}
...
```

dimensions could be an array and not a hash if we want to support multiple dimensions of the same type.

?

**Comment by pudo** [comment]
Ha, this is turning into an actual data model :) But why would you want the type to be a key - rather than the name, or just making it a list, what's the benefit?

**Comment by pwalsh** [comment]
Just reading the current spec and thinking out loud. Not sure it is better.

**Comment by pudo** [comment]
It seems to me like an arbitrary thing to key dimensions by, and I can't think of any pragmatic example of it's benefits. Besides, I wonder what the semantics of type are? "datetime" is a very different category of beast from something more abstract like "entity", which is different again from a specific role like "project"...

**Comment by pwalsh** [comment]
@pudo good question. I suggest opening a ticket for it and @rgrp can respond directly (as he is the current maintainer). 

But as I believe you know, the spec is a collaboration between OKFN, the World Bank, and GIFT.

It is currently being trialled on BOOST data, and we are also collecting EU and AU data for trial (https://github.com/os-data). 

The spec is being worked on here, in public, and any consultation can occur here in the issue tracker.

**Comment by rgrp** [comment]
This was FIXED in a separate issue and commit https://github.com/openspending/fiscal-data-package/commit/6012fca193b1940a8ca17637e10718aa3bb992c2
