### ISSUE TITLE
Limited phase field options

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#46]
I just wanted to forward the WB concern that the proposed options of status/moment/phase/etc. ("proposed", "approved", "adjusted", or "executed") don't necessarily map well to all datasets.  WB suggested that this is a mainly a problem on the expenditure side, whose cycles can vary even between different Latin American countries. cc: @cecilaki

**Comment by pwalsh** [comment]
@danfowler we'll need explicit examples of cycles.

**Comment by jazzido** [comment]
@danfowler, that's a valid concern. As an example, these are the 'expense stages' (*momento del gasto*) for many budget management systems in Argentina:

  - Approved
  - Current (ie, Approved + Modifications)
  - *Preventivo*(can't find the english accounting term for this)

**Comment by danfowler** [comment]
Thanks, @jazzido, that is really helpful.  I renamed the issue to reflect the new name for the property.

Also, I note that @pudo makes the same point [here](https://github.com/openspending/fiscal-data-package/issues/93) about fixed lists in dimensions: 

> There are also more types of phases and directions (the last dataset I added to OHa has directions "revenue", "expenditure", "internal paid", "internal received", "balance").

**Comment by danfowler** [comment]
So, to recap and to add context: broadly speaking, there's a tension between having an agreed-on list of well-defined budget phases for greater comparability between datasets on one hand and expanding the number of options to account for the different budget phases in different governments on the other.  

My sense is that (a) this is something we can push to a future version, if necessary, and (b) we can make the "budget data" appendix more structured so that it is very clear what it means when a user designates a particular measure as "approved" or "executed" etc.

In the meantime, perhaps we can crowdsource a list of budget phases for different governments from the community?  What do you think @jazzido @pudo @rgrp ?

**Comment by rgrp** [comment]
@danfowler this is high level metadata. I would suggest we go for the core list and e.g. `other` if it does not fit. The one alternative would be to have core list and allow users to have their own versions using e.g. `x-{myname}` style (like mimetypes).

I think keep it simple and force a simple list to start with and then examine if this a big problem.

**Comment by danfowler** [comment]
@rgrp AGREED.  Keep it simple for 0.3.0.  Stick the core list, especially given that this is an optional field.
