### ISSUE TITLE
Dimension example improvements

### ISSUE THREAD

**Issue by stevage** [openspending/fiscal-data-package#47]
I'm a bit confused by the examples of dimensions, for example:

> We illustrate here some common dimensions.

`date`

```
"date": {
# note the list of fields is for illustration - you can have any fields you like
  "fields": {
    "year": "source field name"
  }
}
```

Assuming that the enclosing element is `mapping` (it'd also be good if this was clearer - sometimes it's confusing trying to guess where a snippet of code sits exactly), then shouldn't this be:

```
"date": {
  "dimensionType": "datetime",
# note the list of fields is for illustration - you can have any fields you like
  "fields": {
    "year": "source field name"
  }
}
```

Understood that `dimensionType` is "optional", but surely it should be present in the example.

Also, IMHO it's confusing starting with a list of 4 `dimensionType`s, and then having examples that don't really match them - how about an example of the `project` `dimensionType` for instance?

Or maybe the `dimensionType` concept just hasn't been fully fleshed out yet.

**Comment by pwalsh** [comment]
@stevage hi. Just letting you know that @rgrp is not available this week but we'll be getting back to this, specifically issues of mapping/dimensions, next week sometime.
