### ISSUE TITLE
Representing dimensions which are trees, normalised across multiple resources

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#49]
The classic case is functional classification, but it could apply to any dimension potentially (projects, entities, etc.)

How do we use `mapping.{dimension}` to represent a tree, when budget line data has a single field that points to an "object" in another resource? The reference from one resource to another is already provided by the `schema` property on the resource (JSON Table Schema).

* [Here is an example from an older version of this spec work (as OpenSpending Data Package)](https://github.com/openspending/osep/blob/e782aa56c7ae494fbb720a175fba9941208ea0b2/_includes/with-classification/datapackage.json#L1)

**Comment by rgrp** [comment]
The approach i think is that you map in logical model to that normalized table and leave the link inferred from the JTS foreign key

e.g.

```
  "function": {
    "fields": {
      "id": {
          "resource": "function"
          "source": "id"
        },
        "title": {
           "resource": "function",
           "source": "title"
        }
  }
```

Will update example

**Comment by rgrp** [comment]
Not sure if we have already implemented this - need to check.

**Comment by rgrp** [comment]
FIXED / INVALID. Not sure what is outstanding or needed here beyond what we have :-)

**Comment by pwalsh** [comment]
I'm happy with the JTS route, but it would be good to be more explicit in the spec. The example is missing the payee file being referenced: http://fiscal.dataprotocols.org/examples/entities-normalized/
