### ISSUE TITLE
Different measure columns can reflect different values of a dimension

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#60]
In some datasets (e.g. https://github.com/os-data/eu-allocations-per-ms-2014-2020 & https://github.com/os-data/gb-cap-beneficiaries), different columns refer to spending on different programs/projects.  However, we expect to express programs/projects as values in a dimension.  Should we expect this kind of file (A) to be transformed (more or less "paste special tranposed") into the shape we expect (B)?

### A

| Country ID | Cohesion Fund (€) | Less Developed Regions (€) | Transition Regions (€) | More Developed Regions (€) | Outermost and northern sparsely populated regions (€) | European Territorial Cooperation: Cross-Border Cooperation (€) | European Territorial Cooperation: Transnational Cooperation (€) | Youth Employment Initiative (additional allocation) (€) | 
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Poland | 23208000000 | 51163600000 |  | 2242400000 |  | 543200000 | 157300000 | 252400000 |

### B

| Country ID | Fund | Amount |
| ------------- | ------------- | ----- | 
| Poland | Cohesion Fund (€) | 23208000000 |
| Poland | Less Developed Regions (€) | 51163600000 |
| Poland | More Developed Regions (€) | 2242400000 |
| Poland | European Territorial Cooperation: Cross-Border Cooperation (€) | 543200000 |
| Poland | European Territorial Cooperation: Transnational Cooperation (€) | 157300000 |
| Poland | Youth Employment Initiative (additional allocation) (€) | 252400000 |

**Comment by danfowler** [comment]
@pwalsh as far as I understand from our earlier conversation, these datasets are probably outside the realm of the kind of table structure we would expect to deal with.

**Comment by pwalsh** [comment]
I'd say we'd require A to become B.

**Comment by rgrp** [comment]
IMO this should *definitely* be normalized. Those columns are *not* IMO measures. So +1 to @pwalsh and perhaps we should have an example for this listing it as anti-pattern and explaining how it should be transformed.

**Comment by pwalsh** [comment]
@rgrp great.

@danfowler this is truly a great example, can you:

* Fix the relevant data package examples in `os-data`
* Add this, with an explanation, to an examples section on the spec (like: a section of example data that requires pre-processing, or something)

**Comment by danfowler** [comment]
@pwalsh sure, the EU example is pretty straightforward to do manually, but I might need some pointers on transforming the 190,000 lines of GB CAP beneficiaries.

**Comment by pwalsh** [comment]
@danfowler righty-o :).

**Comment by danfowler** [comment]
As a side note, this operation increases the size of the uncompressed, non-normalized CSV, so I can see why people would prefer the original version.

![screen shot 2015-10-14 at 13 40 51](https://cloud.githubusercontent.com/assets/772616/10481441/43ff6ee4-7279-11e5-8233-dd60d6084ff8.png)

**Comment by rgrp** [comment]
@danfowler for the example in this repo you'd just want to pull a small sample of the data right ;-)

@danfowler re size - that's swings and roundabouts and depends on whether you "code" the funds or not (writing out their full name on every row is obviously painful sizewise). But yes, normalizing in this way will increase file size.

**Comment by danfowler** [comment]
@rgrp yes, I added a very, very small sample :)

**Comment by rgrp** [comment]
FIXED - see example in http://fiscal.dataprotocols.org/examples/transform-needed/
