### ISSUE TITLE
"economic" v.s. "chartOfAccounts" classifications

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#65]
I'm not sure about the reasoning behind referring to "economic" classifications as `chartOfAccounts` instead of just simply `economic`.  The IMF and World Bank BOOST seem to default to functional, administrative, and economic classifications as the most basic ways to classify expenditure.

https://www.imf.org/external/pubs/ft/tnm/2009/tnm0906.pdf

**Comment by rgrp** [comment]
@danfowler i renamed economic classification to "chart of accounts" when migrating from http://fiscal.dataprotocols.org/spec/0.2/ as i thought it was clearer. (Being an economist i wasn't clear what an "economic" classification was exactly ;-) ...). If economic classification is the standard terminology we can revert to that ...

**Comment by pwalsh** [comment]
+1 for economic as it is indeed standard terminology.

**Comment by danfowler** [comment]
AGREED, will revert to economic classification.
