### ISSUE TITLE
fiscalPeriod - hash instead of slash?

### ISSUE THREAD

**Issue by stevage** [openspending/fiscal-data-package#68]
Just a quibble, but `fiscalPeriod` is currently defined as "2015-01-1/2015-12-31" format. [My experience with ISO8601](https://github.com/OKFNau/open-council-data/issues/15) formats suggests that:

1. "ISO8601" is not so much a standard as a whole family of possible formats that almost nothing completely supports
2. And hence, there isn't much library support for interpreting strings that don't resolve to a single date (like ranges, recurring intervals etc)
3. And hence, everyone is going to end up having to manually split the string anyway
4. And hence, why not just do:

```
fiscalPeriod: {
  start: '2015-01-01',
  end: '2015-12-31'
}
```

**Comment by pwalsh** [comment]
+1

**Comment by rgrp** [comment]
AGREED will implement change to object.
