### ISSUE TITLE
Handling other kinds of numerical measures (e.g. percentages)

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#69]
Measures are said to *usually* correspond to financial amounts:

    Measures are numerical and usually correspond to financial amounts in the source data. 

But "currency" is a `MUST` property on a measure.

    currency: (MUST) Any valid ISO 4217 currency code.

One of the measures in the [2007-2013 EU Funds Absorption rate](https://github.com/os-data/eu-funds-absorption-rate-2007-2013/blob/master/data/2007-2013_Funds_Absoption_Rate.csv) dataset is absorption rate, which is a percentage which can't usefully be described with a currency nor can it be aggregated the same way (SUM) as other financial amounts.  Should there be a way to describe this kind of measure or should we specify that measures **are always** financial amounts in the source data?

**Comment by rgrp** [comment]
I suggest we do not handle percentage measures and simply discard the data or allow it on the "fact" table as an attribute (what is the use case for processing percentages - as you also say percentages are "bad" measures because they are problematic to aggregate).

**Comment by pwalsh** [comment]
@rgrp @danfowler I'd even say that it doesn't get loaded to a fact table. I think it is reasonable right now to equate measures with *monetary* amounts as fas as Fiscal Data Package is concerned.

**Comment by rgrp** [comment]
WONTFIX. Agreed that we do not handle generally non-financial measures including e.g. percentages.

**Comment by rgrp** [comment]
One fix is to delete "usually" in the spec.
