### ISSUE TITLE
Worked example of analysing data provided in FDP?

### ISSUE THREAD

**Issue by timgdavies** [openspending/fiscal-data-package#71]
An important principle in thinking about adoption of a standard is how it will make it easier for both users and publishers to work with data.

As I read the current FDP, and the [examples](http://fiscal.dataprotocols.org/spec/#examples), I can see how:
- It allows publishers to mark-up their existing data - avoiding the need to convert existing structured CSV data to a new structure (assuming all fields use the required data types);
- It supports common semantic description of those fields without needing to change the headers in the CSV files;

But I'm currently not seeing clear worked examples of how this would increase the usability of the data for users, without requiring access to datapackage aware tooling. 

Is it possible to set out some use cases in the documentation, and to illustrate with examples how specific groups of users benefit from publishers taking the effort to package their data in FDP?

**Comment by pwalsh** [comment]
@timgdavies great points. Yes, we'll work on this over the next weeks

**Comment by akariv** [comment]
Can we close this, or is proper documentation still necessary?

**Comment by timgdavies** [comment]
The language of the examples remains solely technical - and does not currently appear to include use-cases, or fully worked examples of how adopting FDP can be carried out by publishers or users.

**Comment by pwalsh** [comment]
Moving to https://github.com/frictionlessdata/datapackage-fiscal/issues/4
