### ISSUE TITLE
Dimension Type Inconsistency

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#73]
`dimensionType` `MUST` be one of: `datetime`, `entity`, `classification`, `project`.

However, the [tables](http://fiscal.dataprotocols.org/spec/#aggregated-expenditure-data) in the special dimensions section at the bottom suggests that dimensions can have types like **"Date"**, "Entity", "Classification", "Project", **"Fact"**, and **"Location"**.

It would be good to harmonize these.

**Comment by danfowler** [comment]
@stevage already pointed this out #47

**Comment by rgrp** [comment]
Reopening. Fix is:

* Add: "fact", "location" and "other" to dimension types
* Change: "Date" to DateTime in table ...
* Change: lowercase dimension types in table
