### ISSUE TITLE
Multiple Currencies Example

### ISSUE THREAD

**Issue by rufuspollock** [openspending/fiscal-data-package#76]
Example how to deal with a dataset with multiple currencies (or clarify we don't deal with it).

**Comment by pwalsh** [comment]
* We might want to accept a scenario where each measure is a different currency of the same thing (basically, some hardcoded exchange rate)
* We probably don't want a scenario where a single measure can be in multiple currencies

**Comment by timgdavies** [comment]
Are there source datasets which provide data in multiple currencies to point to? Discussion this from supply side examples I suspect would be useful. 

Not sure if it is relevant to any of the cases of source data, but in IATI an important attribute of transactions is the value-date (i.e. the date which should be used for currency conversion, which is not always the date of the transaction itself if a secondary currency value has been given based on a conversion).

**Comment by rgrp** [comment]
@timgdavies I believe a Chilean example has this but I'm not sure we have one already worked up /cc @danfowler 

Good point on value-date - basically this relates to a much bigger discussion of handling numeraire "currency" (i.e. converting to a standard currency and time e.g. 2001 USD or even PPP 2001 USD) - see https://github.com/openspending/openspending/issues/284 for more on this

**Comment by danfowler** [comment]
@rgrp @timgdavies we have no Chilean example for this, and I can't think of a dataset right now that has multiple currencies

**Comment by jazzido** [comment]
[Chile's procurement site](https://www.mercadopublico.cl/Home) certainly uses multiple currencies. I've seen public tenders published in Chilean peso, US Dollar and *Unidad de Fomento* (an inflation-adjusted chilean currency used in public tendering.)

**Comment by rgrp** [comment]
@jazzido are these the same transaction presented in multiple currencies or different transactions within the same dataset in different currencies

And welcome btw :-) - great to have your participation!

**Comment by jazzido** [comment]
> @jazzido are these the same transaction presented in multiple currencies or different transactions within the same dataset in different currencies?

AFAIK, a transaction or budget line is presented in a single currency.

> And welcome btw :-) - great to have your participation!

Thanks!

**Comment by rgrp** [comment]
@jazzido ok great - because i have seen budgets where they have the same line but put both the local value and the equivalent us dollar value.

**Comment by danfowler** [comment]
OK, in a dataset where a single budget line has two "amount" columns with two different currencies, a different currency can be modeled for each measure very easily in our current specification. 

As I read this issue now, the explicit ask is for a dataset that has multiple currencies within **one** column where presumably, the `currency` information comes from a different column (per https://github.com/openspending/osep/issues/29#issuecomment-134131272)

If this is the case, then perhaps we are actually looking for a general solution to https://github.com/openspending/fiscal-data-package/issues/91 where attributes of a measure, in addition to the measure itself, get their values from `field`s in the source CSV.

Do I have this right @rgrp ?

cc: @pwalsh

**Comment by rgrp** [comment]
@danfowler that's right. I have to say I'd put this relatively low priority right now and push into v0.4 awaiting a nice concrete example.

**Comment by danfowler** [comment]
@rgrp OK, so pushing this and #91 to v0.4 milestone.

**Comment by akariv** [comment]
I can think of 3 different data sets (2 related to procurements and another related to political donations) having currency as a separate column.

When we think of a solution to this, let's consider the more generic case which is having two measures, each with its own currency column.
One option would be to add a `currencyRef` property to a measure which would hold the identifier of the dimension that contains the currency information.

(Also related to #139)

**Comment by rgrp** [comment]
@akariv can you link  to these specific examples.

**Comment by akariv** [comment]
Yes, here are a few from Israel (Google auto-translate to English works reasonably enough in them):
1. https://foi.gov.il/he/node/2482
   This is spending data from Israel's FOIA portal (there's one such file per ministry per quarter).
   Column M in the downloadable excel file is the currency.
2. http://www.mr.gov.il/ExemptionMessage/Pages/SearchExemptionMessages.aspx
    This is the government's transparency portal for exempt-from-tender procurements.
    Each item in the HTML table leads to a detail view, in which the sum and currency are specified.
3. https://statements.mevaker.gov.il/GuarantyDonationPublisher/GuarantyDonationPublisher.aspx
    This dataset is for donations to candidates in party primary elections. 
    Here you have two columns, one for the amount in NIS and another for 'foreign currency donations', which states the amount and the currency.

**Comment by pwalsh** [comment]
Moved to https://github.com/frictionlessdata/datapackage-fiscal/issues/6
