### ISSUE TITLE
Quality levels in parentheses

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#77]
Some examples have a quality level that is in brackets/parens.  Does this mean anything specifically?

| Dimension | Type | Quality | Description |
|----|---|---|---|
| ... | ... | ... | ... |
| recipient | entity | 2 | The recipient (if any) targetted by the revenue item. |
| source | location | (3) | Geographical region from which the revenue item originates.|

**Comment by rgrp** [comment]
This was intended to show these were desirable but not required to reach that quality level.

**Comment by danfowler** [comment]
OK, I will write a pull request that adds this clarification.
