### ISSUE TITLE
Reintroduce "profiles" hash and its use

### ISSUE THREAD

**Issue by rgrp** [openspending/fiscal-data-package#82]
We removed this as a simplification in v0.3-alpha-1. I think we can add back and make it SHOULD rather than MUST.

**Comment by danfowler** [comment]
+1

**Comment by rgrp** [comment]
@danfowler do you want to implement in a PR and we review and add.

**Comment by danfowler** [comment]
Yes

**Comment by danfowler** [comment]
Closed by https://github.com/openspending/fiscal-data-package/commit/b19b7af537bc80d12f4563c9ad9580fa5d9eef9f
