### ISSUE TITLE
Make "name" in a measure or dimension field unique and URL-compatible

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#90]
It is not made explicit in the spec that the `name` in a given measure or field in a dimension in a FDP must be unique and url-compatible.  These requirements would be useful in referring to measures and fields in a dimension in an implementation (see: https://github.com/openspending/fiscal-data-package/issues/48#issuecomment-148414475 by @pudo).  These constraints would come for free if measures and fields in a dimension were reverted back to objects (see: https://github.com/openspending/fiscal-data-package/issues/48#issuecomment-158681781 by @pwalsh).  

- The original [change from object to array](https://github.com/openspending/fiscal-data-package/commit/9236725314514d661596becaac5bba27b4653f31) and justification.
- Example of issue: https://github.com/openspending/fiscal-data-packager/issues/34

**Comment by rgrp** [comment]
I'm not sure why making these objects would guarantee url-compatibility.

On general point: +1. Re reverting to objects I'm doubtful as I think order is (marginally) useful and it does not matter too much either way.

Happy with any resolution here but i note object reversion is a breaking change.

**Comment by pwalsh** [comment]
This already happened.
