### ISSUE TITLE
Make dimension attributes an array of objects, each mapping several logical model fields to source CSV columns

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#97]
Adapted with slight modification from this comment by @pwalsh: https://github.com/openspending/fiscal-data-package/issues/48#issuecomment-158681781

- Includes change of `fields` to `attributes` suggested here: https://github.com/openspending/fiscal-data-package/issues/93
- Includes partial reversion from fields as array elements to fields as object elements: https://github.com/openspending/fiscal-data-package/issues/94

Reasoning for this change:
- It is currently harder than it should be apply levels using the level keyword.  That is, an implementer has to make a (somewhat arbitrary) choice as to what number to assign what level when all we want to do is determine relative position:  (see: https://github.com/os-data/boost-paraguay/commit/a04e4f57c42f76890f1bd2ed673e0f1e780dffb9)
- Multiple comments by @pudo and @pwalsh that using objects where possible provide benefits that simple arrays don't: https://github.com/openspending/fiscal-data-package/issues/93

```
# non-hierarchical dimension with one attribute mapping to several source fields
{
  "name": "function",
  "dimensionType": "classification",
  "attributes": [
    {
      "id": {
        "source": "function1_code"
      },
      "title": {
        "source": "function1_name"
      }
    }
  ]
}

# hierarchical dimension with several attributes mapping to several source fields
{
  "name": "function",
  "dimensionType": "classification",
  "attributes": [
    {
      "id": {
        "source": "function1_code"
      },
      "title": {
        "source": "function1_name"
      }
    },
    {
      "id": {
        "source": "function2_code"
      },
      "title": {
        "source": "function2_name"
      }
    }
  ]
}
```

If `attributes` is length == 1, we have a flat dimension object. if `attributes` is length > 1, we have an indexed hierarchy of dimension objects.

**Comment by jazzido** [comment]
I've only read the FDP spec superficially, but I sense that a lot of its features resemble an OLAP schema definition language. Maybe you already have, but I suggest taking a look at [Mondrian's 4 schema definition language](http://mondrian.pentaho.com/head/documentation/schema.php#Schema_element) for inspiration.

If it helps, I can share some of the Mondrian schemas that I'm using for budget data in [*Presupuesto Abierto*](http://bahia.presupuestoabierto.org).
